### ISSUE TITLE
inverted hound's legs faces issue

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4/Thirdym#16]
one of the hound's legs faces randomly got inverted
![going funny](https://user-images.githubusercontent.com/90115354/132111954-1bdfdc7b-793e-44e0-887c-928c79482a42.png)
![going funny the sequel](https://user-images.githubusercontent.com/90115354/132111956-d8079629-3e62-47b4-b480-3e164a7d5bca.png)

**Comment by Gann4** [comment]
3D art doesn't have a high priority and these models are not mine, prototype stuff and unfinished features in sandbox mode are low priority stuff to do. :)
