### ISSUE TITLE
lightning system issue

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4/Thirdym#17]
i randomly found this darker version of me, probably the manual lightning system
![darker version](https://user-images.githubusercontent.com/90115354/132112044-ef507b49-0de7-4987-99d5-7798538a539d.png)

**Comment by Gann4** [comment]
Setting up lighting manually for baked lightmaps takes too much time for a map that doesn't really have a purpose for the game, this could be more important if it was a game level or a training map.
